src/euphoria/euphoria/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("web.urls", namespace="web")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/euphoria/web/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import index,registerPage,logoutPage, accountPage, categoryPage, productPage, wishlistPage, cartPage, add_to_cart, wishlist, upload_photo



app_name = "web"

urlpatterns = [
    path ('', index, name="home"),
    path('register/', registerPage, name="register"),
    path('logout/', logoutPage, name='logout'),
    path('account/', accountPage, name='account'),
    path('category/<int:category_id>/', categoryPage, name='category'),
    path('product/<int:product_id>/', productPage, name='product'),
    path('wish/<int:product_id>/', wishlist, name='wishlist'),
    path('wishlist/', wishlistPage, name='wishlistPage'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', cartPage, name='cart'),
    path('upload/', upload_photo , name='upload_photo'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/euphoria/web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Category(models.Model):
    GENDER_CHOICES=[
        ('M', 'MEN'),
        ('W', 'WOMEN')
    ]
    name = models.CharField(max_length=255,)
    image = models.ImageField(upload_to='category_image/',blank=False, null=False)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)


    def __str__(self):
        return self.name
    

class Product(models.Model):
    SIZE_CHOICES = [
        ('XS', 'Extra Small'),
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
        ('XS', 'Extra Small'),
        ('XS', 'Extra Small'),
    ]
    COLOR_CHOICES = [
        ('reb', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('black', 'Black'),
    ]
    name = models.CharField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,  unique=True)
    image = models.ImageField(upload_to='Product/',blank=False, null=False)
    brand = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="product")
    rating = models.FloatField(default=0.0)
    buy_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    date_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class meta:
        unique_together = ('user', 'product')

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class meta:
        unique_together = ('user', 'product')

src/euphoria/web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', ]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

src/euphoria/web/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from web.models import Category, Product, Profile, Cart, Wishlist
from django.contrib.auth.decorators import login_required
from web.forms import CreateUserForm, ProfileForm



def index(request):
    categories_of_men = Category.objects.filter(gender='M')
    categories_of_women = Category.objects.filter(gender='W')
    product = Product.objects.order_by('-buy_count')[:4]
    new_arrival = Product.objects.order_by('-date_time')[:6]
    user_wishlist = []
    profile = None
    if request.user.is_authenticated:
        profile, created = Profile.objects.get_or_create(user=request.user)
        user_wishlist = Wishlist.objects.filter(user=request.user).values_list('product_id', flat=True)

    return render(request,"index.html",{'categories_of_men' : categories_of_men, 'categories_of_women' : categories_of_women,  'user_wishlist':user_wishlist, 'product':product, 'new_arrival':new_arrival, 'profile':profile})


def registerPage(request):
    
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login') 
        

    return render(request, 'accounts/register.html', {'form':form})

@login_required
def upload_photo(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('web:account')  
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'upload_photo.html', {'form': form})

def logoutPage(request):
    logout(request)
    return redirect('login')

def accountPage(request):
    if request.user.is_authenticated:
        profile, created = Profile.objects.get_or_create(user=request.user)
        return render(request, 'accounts/accounts.html', {'profile': profile})
    else:
        return redirect('login')

def categoryPage(request, category_id):
    category = Category.objects.get(id=category_id)
    product = Product.objects.filter(category=category)
    user_wishlist = []
    if request.user.is_authenticated:
        user_wishlist = Wishlist.objects.filter(user=request.user).values_list('product_id', flat=True)
    return render(request, 'category.html', {'category' : category, 'products' : product, 'user_wishlist':user_wishlist})

def productPage(request, product_id):
    product = Product.objects.get(id=product_id)
    same_category = Product.objects.filter(category=product.category )
    all_product = Product.objects.all()
    if request.user.is_authenticated:
        user_wishlist = Wishlist.objects.filter(user=request.user).values_list('product_id', flat=True)
    else:
        user_wishlist = []

    return render(request, 'product.html', {'product' : product, 'same_category' : same_category, 'all_product':all_product, 'user_wishlist':user_wishlist })

@login_required
def wishlist(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    wishlist_item, created = Wishlist.objects.get_or_create(user=request.user, product=product)

    if not created:
        wishlist_item.delete()  

    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def wishlistPage(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    user_wishlist = Wishlist.objects.filter(user=request.user).values_list('product_id', flat=True)


    return render(request, 'wishlist.html', {'wishlist_items':wishlist_items, 'user_wishlist': user_wishlist,})



@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    Cart.objects.get_or_create(user=request.user, product=product)
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required
def cartPage(request):
    cart_items = Cart.objects.filter(user=request.user)
    user_wishlist = Wishlist.objects.filter(user=request.user).values_list('product_id', flat=True)
    return render(request, 'cart.html', {'cart_items':cart_items, 'user_wishlist': user_wishlist,})

src/euphoria/templates/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Euphoria</title>
    <link rel="icon" href="{% static 'img/Euphoria.svg' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/tailwindcss.js' %}"></script>
</head>
<body>
<!-- Header -->
 <header class="w-full overflow-x-hidden px-4 sm:px-6 lg:px-8">
        <div class="w-[90%] mx-auto flex justify-between items-center py-4">
            <div class="flex gap-4">
            <div class="lg:hidden " id="menuBar">
                <img src="{% static 'img/menu.svg' %}" alt="" />
            </div>
            <a class="" href="">
                <img class="26px"  src="{% static 'img/Euphoria.svg' %}" alt="" />
            </a>
            </div>
            <div class="hidden lg:flex space-x-6">
            <a class="text-xl  text-gray-600" href="">Shop</a>
            <a class="text-xl text-gray-600" href="">Men</a>
            <a class="text-xl text-gray-600" href="">Women</a>
            <a class="text-xl text-gray-600" href="">Combos</a>
            <a class="text-xl text-gray-600" href="">Joggers</a>
            </div>
            <div class=" hidden md:flex  border border-gray-300 rounded-lg py-2 px-4 "  id="searchBar">
            <img class="mx-1.5" src="{% static 'img/search.svg' %}" alt="" />
            <input type="search" placeholder="Search" class="border-none" />
            </div>
            <div class="flex gap-2">
            <span class="md:hidden"  onclick="toggleSearch()"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/search.svg' %}" alt="" /></span>
            {% if user.is_authenticated %} 
            <a href="{% url 'web:wishlistPage' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/wishlist.svg' %}" alt="" /></a>
            {% else %}
            <a href="{% url 'login' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/wishlist.svg' %}" alt="" /></a>
            {% endif %}
            <a href="{% url 'web:account' %}" id="profile">
                {% if profile and profile.photo %}
                    <img src="{{ profile.photo.url }}" alt="profile photo" class="w-8 h-8 rounded-lg object-cover" />
                {% else %}
                    <a href="{% url 'web:upload_photo' %}">
                    <img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/profile.svg' %}" alt="Default Avatar" />
                    </a>
                {% endif %}
            </a>
            {% if user.is_authenticated %} 
            <a href="{% url 'web:cart' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/add-cart.svg' %}" alt="" /></a>
            {% else %}
            <a href="{% url 'login' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/add-cart.svg' %}" alt="" /></a>
            {% endif %}
            </div>
        </div>
        <div class="hidden md:hidden bg-gray-700 text-center w-full " id="Toggle">
            <img id="toggle-close" class="h-8" src="{% static 'img/close.svg' %}" alt="" />
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Shop</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Men</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Women</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Combos</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Joggers</a>
        </div>
    </header>
<!-- /Header -->
<!-- product -->
<div class="w-full my-8">
    <div class="w-[90%] py-16 mx-auto text-left">
        <a class="text-xl" href="{% url 'web:home' %}">Home</a>
        <span class="text-xl">/Cart</span>
    </div>
    <div class="w-[90%] mx-auto">
        {% if cart_items %}
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-2">
            {% for item in cart_items %}
            <a href="{% url 'web:product' item.product.id %}">
            <div>
                <div class="relative inline-block ">
                    <img class="w-full h-96" src="{{ item.product.image.url }}" alt="{{ item.product.name }}" >
                    <div class="absolute top-2 right-2">
                        {% if product.id in user_wishlist %}
                        <form method="post" action="{% url 'web:wishlist' item.product.id %}">
                            {% csrf_token %}
                            <button type="submit">
                                <img class="p-2 rounded-full  bg-red-400" src="{% static 'img/wishlist.svg' %}" alt="wishlistIcon">
                            </button>
                        </form>
                    {% else %}
                        <form method="post" action="{% url 'web:wishlist' item.product.id %}">
                            {% csrf_token %}
                            <button type="submit">
                                <img class="p-2 rounded-full  bg-gray-300" src="{% static 'img/wishlist.svg' %}" alt="wishlistIcon">
                            </button>
                        </form>
                    {% endif %}
                    </div>
                    <div class="my-2 relative">
                        <span class="text-base">{{ item.product.name }}</span>
                        <br/>
                        <span class="text-sm text-gray-500">{{ item.product.brand }}</span>
                        <div class="w-16 h-8 bg-[#F6F6F6] absolute top-2 right-2 rounded-lg flex justify-center items-center">
                            <span>${{ item.product.price }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
            {% endfor %}
        </div>
        {% else %}
            <div class="text-xl text-center py-10 text-gray-500">
                <P>Your cart is empty.</P>
            </div>
        {% endif %}
    </div>
</div>
<!-- /product -->
<!-- Footer -->
<footer class="bg-gray-900 text-gray-300 py-12">
    <div class="w-[90%] mx-auto px-6 py-6 grid grid-cols-1 md:grid-cols-4 gap-8 border-b-[1px] border-[#BEBCBD]">
        <div>
            <h4 class="text-lg font-semibold text-white mb-4">Need Help</h4>
            <ul class="space-y-2">
                <li><a href="#" class="hover:text-white">Contact Us</a></li>
                <li><a href="#" class="hover:text-white">Track Order</a></li>
                <li><a href="#" class="hover:text-white">Returns & Refunds</a></li>
                <li><a href="#" class="hover:text-white">FAQs</a></li>
                <li><a href="#" class="hover:text-white">Career</a></li>
                
            </ul>
            <div class="mt-16">
                <div class="flex gap-4">
                    <a href=""><img src="{% static 'img/facebook.svg' %}" alt=""></a>
                    <a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a>
                    <a href=""><img src="{% static 'img/twitter.svg' %}" alt=""></a>
                    <a href=""><img src="{% static 'img/linkedin.svg' %}" alt=""></a>
                </div>
                </div>
        </div>
        <div>
            <h4 class="text-lg font-semibold text-white mb-4">Company</h4>
            <ul class="space-y-2">
                <li><a href="#" class="hover:text-white">About Us</a></li>
                <li><a href="#" class="hover:text-white">Euphoria Blog</a></li>
                <li><a href="#" class="hover:text-white">Collaboration</a></li>
                <li><a href="#" class="hover:text-white">Media</a></li>
            </ul>
        </div>
        <div>
            <h4 class="text-lg font-semibold text-white mb-4">More Info</h4>
            <ul class="space-y-2">
                <li><a href="#" class="hover:text-white">Terms and Conditions</a></li>
                <li><a href="#" class="hover:text-white">Privacy Policy</a></li>
                <li><a href="#" class="hover:text-white">Shipping Policy</a></li>
                <li><a href="#" class="hover:text-white">Sitemap</a></li>
            </ul>
        </div>
        <div>
            <h4 class="text-lg font-semibold text-white mb-4">Location</h4>
            <p class="text-sm">support@euphoria.in</p>
            <p class="text-sm">Eklingpura Chouraha, Ahmedabad Main Road</p>
            <p class="text-sm">INH 8 - Near Mahadev Hotel, Udaipur, India- 313002</p>
            <div class="mt-16">
            <h4 class="text-lgvmd:text-sm font-semibold text-white mt-6 mb-4">Download The App</h4>
            <div class="flex gap-2 ">
                <img src="{% static 'img/google-play.svg' %}" alt="Google Play" class="w-24 md:w-16">
                <img src="{% static 'img/app-store.svg' %}" alt="App Store" class="w-24 md:w-16">
            </div>
            </div>
        </div>
    </div>
    <div class="w-[90%] mx-auto">
        <select class="w-full py-4 bg-transparent border-b-[1px] border-b-[#BEBCBD] text-2xl font-extrabold" name="" id="">
            <option  class="w-50 text-black text-2xl" value="">Popular Categories</option>
            <option class="w-50 bg-white text-black" value="">Popular Categories</option>
        </select>
    </div>
    <div class="text-center text-sm text-gray-500 mt-8 ">
        <p>Copyright © 2023 Euphoria Folks Pvt Ltd. All rights reserved.</p>
    </div>
</footer>
<!-- /Footer -->
<script src=""></script>
</body>
</html>

src/euphoria/templates/category.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{category.name}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="icon" href="{% static 'img/Euphoria.svg' %}" />
    <script src="{% static 'js/tailwindcss.js' %}"></script>
</head>
    <!-- Header -->
     <header class="w-full overflow-x-hidden px-4 sm:px-6 lg:px-8">
        <div class="w-[90%] mx-auto flex justify-between items-center py-4">
            <div class="flex gap-4">
            <div class="lg:hidden " id="menuBar">
                <img src="{% static 'img/menu.svg' %}" alt="" />
            </div>
            <a class="" href="">
                <img class="26px"  src="{% static 'img/Euphoria.svg' %}" alt="" />
            </a>
            </div>
            <div class="hidden lg:flex space-x-6">
            <a class="text-xl  text-gray-600" href="">Shop</a>
            <a class="text-xl text-gray-600" href="">Men</a>
            <a class="text-xl text-gray-600" href="">Women</a>
            <a class="text-xl text-gray-600" href="">Combos</a>
            <a class="text-xl text-gray-600" href="">Joggers</a>
            </div>
            <div class=" hidden md:flex  border border-gray-300 rounded-lg py-2 px-4 "  id="searchBar">
            <img class="mx-1.5" src="{% static 'img/search.svg' %}" alt="" />
            <input type="search" placeholder="Search" class="border-none" />
            </div>
            <div class="flex gap-2">
            <span class="md:hidden"  onclick="toggleSearch()"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/search.svg' %}" alt="" /></span>
            {% if user.is_authenticated %} 
            <a href="{% url 'web:wishlistPage' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/wishlist.svg' %}" alt="" /></a>
            {% else %}
            <a href="{% url 'login' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/wishlist.svg' %}" alt="" /></a>
            {% endif %}
            <a href="{% url 'web:account' %}" id="profile">
                {% if profile and profile.photo %}
                    <img src="{{ profile.photo.url }}" alt="profile photo" class="w-8 h-8 rounded-lg object-cover" />
                {% else %}
                    <a href="{% url 'web:upload_photo' %}">
                    <img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/profile.svg' %}" alt="Default Avatar" />
                    </a>
                {% endif %}
            </a>
            {% if user.is_authenticated %} 
            <a href="{% url 'web:cart' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/add-cart.svg' %}" alt="" /></a>
            {% else %}
            <a href="{% url 'login' %}"><img class="px-2 py-2 bg-gray-100 rounded-lg w-8" src="{% static 'img/add-cart.svg' %}" alt="" /></a>
            {% endif %}
            </div>
        </div>
        <div class="hidden md:hidden bg-gray-700 text-center w-full " id="Toggle">
            <img id="toggle-close" class="h-8" src="{% static 'img/close.svg' %}" alt="" />
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Shop</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Men</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Women</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Combos</a>
            <a class="block px-4 py-2 text-gray-100 hover:bg-gray-300" href="">Joggers</a>
        </div>
    </header>
    <!-- /Header -->
    <!-- product -->
    <div class="w-full my-8">
        <div class="w-[90%] py-16 mx-auto text-left">
            <a class="text-xl" href="{% url 'web:home' %}">Home</a>
            <span class="text-xl text-gray-500">{% if category.gender == 'M' %}
                / Men
                {% elif category.gender == 'W' %}
                / Women
                {% endif %}
            </span>
            <span class="text-xl">/ {{category.name}}</span>
        </div>
        <div class="w-[90%] mx-auto">
            <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-2">
                {% for product in products %}
                <a href="{% url 'web:product' product.id %}">
                <div>
                    <div class="relative inline-block ">
                        <img class="w-full h-96 rounded-lg" src="{{ product.image.url }}" alt="{{ product.name }}" >
                        <div class="absolute top-2 right-2">
                            {% if user.is_authenticated %}
                                {% if product.id in user_wishlist %}
                                    <form method="post" action="{% url 'web:wishlist' product.id %}">
                                        {% csrf_token %}
                                        <button type="submit">
                                            <img class="p-2 rounded-full  bg-red-400" src="{% static 'img/wishlist.svg' %}" alt="wishlistIcon">
                                        </button>
                                    </form>
                                {% else %}
                                    <form method="post" action="{% url 'web:wishlist' product.id %}">
                                        {% csrf_token %}
                                        <button type="submit">
                                            <img class="p-2 rounded-full  bg-gray-300" src="{% static 'img/wishlist.svg' %}" alt="wishlistIcon">
                                        </button>
                                    </form>
                                {% endif %}
                            {% else %}
                                    <form method="post" action="{% url 'login'%}">
                                        {% csrf_token %}
                                        <button type="submit">
                                            <img class="p-2 rounded-full  bg-gray-300" src="{% static 'img/wishlist.svg' %}" alt="wishlistIcon">
                                        </button>
                                    </form>
                            {% endif %}
                        </div>
                        <div class="my-2 relative">
                            <span class="text-base">{{ product.name }}</span>
                            <br/>
                            <span class="text-sm text-gray-500">{{ product.brand }}</span>
                            <div class="w-16 h-8 bg-[#F6F6F6] absolute top-2 right-2 rounded-lg flex justify-center items-center">
                                <span>${{ product.price }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- /product -->
    <!-- Footer -->
    <footer class="bg-gray-900 text-gray-300 py-12">
        <div class="w-[90%] mx-auto px-6 py-6 grid grid-cols-1 md:grid-cols-4 gap-8 border-b-[1px] border-[#BEBCBD]">
            <div>
                <h4 class="text-lg font-semibold text-white mb-4">Need Help</h4>
                <ul class="space-y-2">
                    <li><a href="#" class="hover:text-white">Contact Us</a></li>
                    <li><a href="#" class="hover:text-white">Track Order</a></li>
                    <li><a href="#" class="hover:text-white">Returns & Refunds</a></li>
                    <li><a href="#" class="hover:text-white">FAQs</a></li>
                    <li><a href="#" class="hover:text-white">Career</a></li>
                    
                </ul>
                <div class="mt-16">
                    <div class="flex gap-4">
                        <a href=""><img src="{% static 'img/facebook.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'img/twitter.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'img/linkedin.svg' %}" alt=""></a>
                    </div>
                    </div>
            </div>
            <div>
                <h4 class="text-lg font-semibold text-white mb-4">Company</h4>
                <ul class="space-y-2">
                    <li><a href="#" class="hover:text-white">About Us</a></li>
                    <li><a href="#" class="hover:text-white">Euphoria Blog</a></li>
                    <li><a href="#" class="hover:text-white">Collaboration</a></li>
                    <li><a href="#" class="hover:text-white">Media</a></li>
                </ul>
            </div>
            <div>
                <h4 class="text-lg font-semibold text-white mb-4">More Info</h4>
                <ul class="space-y-2">
                    <li><a href="#" class="hover:text-white">Terms and Conditions</a></li>
                    <li><a href="#" class="hover:text-white">Privacy Policy</a></li>
                    <li><a href="#" class="hover:text-white">Shipping Policy</a></li>
                    <li><a href="#" class="hover:text-white">Sitemap</a></li>
                </ul>
            </div>
            <div>
                <h4 class="text-lg font-semibold text-white mb-4">Location</h4>
                <p class="text-sm">support@euphoria.in</p>
                <p class="text-sm">Eklingpura Chouraha, Ahmedabad Main Road</p>
                <p class="text-sm">INH 8 - Near Mahadev Hotel, Udaipur, India- 313002</p>
                <div class="mt-16">
                <h4 class="text-lgvmd:text-sm font-semibold text-white mt-6 mb-4">Download The App</h4>
                <div class="flex gap-2 ">
                    <img src="{% static 'img/google-play.svg' %}" alt="Google Play" class="w-24 md:w-16">
                    <img src="{% static 'img/app-store.svg' %}" alt="App Store" class="w-24 md:w-16">
                </div>
                </div>
            </div>
        </div>
        <div class="w-[90%] mx-auto">
            <select class="w-full py-4 bg-transparent border-b-[1px] border-b-[#BEBCBD] text-2xl font-extrabold" name="" id="">
                <option  class="w-50 text-black text-2xl" value="">Popular Categories</option>
                <option class="w-50 bg-white text-black" value="">Popular Categories</option>
            </select>
        </div>
        <div class="text-center text-sm text-gray-500 mt-8 ">
            <p>Copyright © 2023 Euphoria Folks Pvt Ltd. All rights reserved.</p>
        </div>
    </footer>
    <!-- /Footer -->
</body>
</html>

src/euphoria/templates/upload_photo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Euphoria</title>
    <link rel="icon" href="{% static 'img/Euphoria.svg' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/tailwindcss.js' %}"></script>
</head>
<body>
    <div class="min-h-screen flex items-center justify-center bg-gray-50 px-4">
        <div class="bg-black text-white shadow-md rounded-lg p-6 w-full max-w-md">
            <h1 class="text-2xl font-semibold mb-4 text-center">Upload Your Profile Photo</h1>
            <form method="post" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition">
                Upload
            </button>
            </form>
            </div>
        </div>
</body>
</html>